apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  project: default
  source:
    chart: test
    repoURL: https://github.com/sangheee/testchart
    targetRevision: v0.0.0
    path: test
    helm:
      releaseName: test-release
  destination:
    server: "https://kubernetes.default.svc"
