name: Renovate

on: 
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
#   schedule:
#     # The "*" (#42, asterisk) character has special semantics in YAML, so this
#     # string has to be quoted.
#     - cron: '*/10 * * * *'

env:
  LOG_LEVEL: info
  DRY_RUN: false

  
jobs:
  renovate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Override default config from dispatch variables
        run: |
          echo "DRY_RUN=${{ github.event.inputs.dryRun || env.DRY_RUN }}" >> "$GITHUB_ENV"
          echo "LOG_LEVEL=${{ github.event.inputs.logLevel || env.LOG_LEVEL }}" >> "$GITHUB_ENV"        
          
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.241.11
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
