name: Renovate

on: 
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
#   schedule:
#     # The "*" (#42, asterisk) character has special semantics in YAML, so this
#     # string has to be quoted.
#     - cron: '*/10 * * * *'
jobs:
  renovate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.240.5
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
